name: Build and deploy Node.js app to Azure Web App - SalesInquiryGroup

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - name: Set up Node.js version
        uses: actions/setup-node@v3
        with:
          node-version: '20.x'

      - name: Install dependencies
        run: npm install

      - name: Create simplified build script
        run: |
          cat > build.js << 'EOF'
          const { execSync } = require('child_process');
          const fs = require('fs');
          const path = require('path');

          console.log('Starting simplified build process...');

          // Create dist directory
          const distDir = path.resolve(__dirname, 'dist');
          if (!fs.existsSync(distDir)) {
            fs.mkdirSync(distDir, { recursive: true });
          }
          
          const publicDir = path.resolve(distDir, 'public');
          if (!fs.existsSync(publicDir)) {
            fs.mkdirSync(publicDir, { recursive: true });
          }

          // Copy client files to dist/public
          console.log('Copying client files...');
          try {
            execSync('cp -r client/* dist/public/', { stdio: 'inherit' });
            // Create a simple index.html if it doesn't exist
            if (!fs.existsSync(path.resolve(publicDir, 'index.html'))) {
              fs.writeFileSync(
                path.resolve(publicDir, 'index.html'),
                '<html><body><div id="root"></div><script src="src/main.tsx"></script></body></html>'
              );
            }
          } catch (error) {
            console.error('Failed to copy client files:', error);
            process.exit(1);
          }

          // Build backend
          console.log('Building backend...');
          try {
            execSync('npx esbuild server/index.ts --platform=node --packages=external --bundle --format=esm --outdir=dist', { stdio: 'inherit' });
          } catch (error) {
            console.error('Failed to build backend:', error);
            process.exit(1);
          }

          console.log('Build completed successfully!');
          EOF

      - name: Run simplified build
        run: node build.js

      - name: Zip artifact for deployment
        run: zip release.zip ./* -r

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: node-app
          path: release.zip

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    permissions:
      id-token: write #This is required for requesting the JWT

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: node-app

      - name: Unzip artifact for deployment
        run: unzip release.zip

      - name: Login to Azure
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_GUID }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_GUID }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_GUID }}

      - name: 'Deploy to Azure Web App'
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v2
        with:
          app-name: 'SalesInquiryGroup'
          slot-name: 'Production'
            
