name: Build and deploy Node.js app to Azure Web App - SalesInquiryGroup

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20.x'
          cache: 'npm'

      - name: Install root dependencies
        run: |
          echo "Installing root dependencies..."
          npm ci --no-audit
        env:
          NODE_OPTIONS: "--max_old_space_size=4096"

      - name: Verify critical dependencies
        run: |
          echo "Verifying critical dependencies..."
          # Create a list of required dependencies
          DEPS=(
            "react"
            "react-dom"
            "wouter"
            "lucide-react"
            "react-icons"
            "@tanstack/react-query"
            "firebase"
            "gapi-script"
            "papaparse"
            "@hookform/resolvers"
            "react-hook-form"
            "zod"
            "date-fns"
            "express"
            "recharts"
          )
          
          # Check each dependency and install if missing
          for DEP in "${DEPS[@]}"; do
            if [ ! -d "node_modules/$DEP" ]; then
              echo "Installing missing dependency: $DEP"
              npm install "$DEP"
            else
              echo "✓ $DEP is installed"
            fi
          done
        env:
          NODE_OPTIONS: "--max_old_space_size=4096"

      - name: Debug dependency structure
        run: |
          echo "Debugging dependency structure..."
          ls -la node_modules/@hookform
          ls -la node_modules/firebase
          ls -la node_modules/papaparse
          ls -la node_modules/recharts || echo "recharts not found"
          
          # Check for nested dependencies
          find node_modules -name "resolvers" | grep hookform
          find node_modules -name "auth" | grep firebase
          
          # Check package.json resolution
          echo "Checking package resolution..."
          node -e "console.log('Firebase:', require.resolve('firebase/auth'))"
          node -e "console.log('Hookform:', require.resolve('@hookform/resolvers/zod'))"
          node -e "console.log('Papaparse:', require.resolve('papaparse'))"
          node -e "console.log('Recharts:', require.resolve('recharts'))" || echo "Recharts not resolvable"

      - name: Build application with verbose logging
        run: |
          echo "Building application with verbose logging..."
          # Set environment variable for more verbose Vite output
          export VITE_DEBUG=true
          # Run build with --debug flag
          npm run build -- --debug
        env:
          NODE_ENV: production
          NODE_OPTIONS: "--max_old_space_size=8192"

      - name: Create deployment package
        run: |
          echo "Creating deployment package..."
          
          # Create deployment directory
          mkdir -p deployment
          
          # Copy essential files
          cp -r dist deployment/
          
          # Create web.config for Azure
          cat > deployment/web.config << EOF
          <?xml version="1.0" encoding="utf-8"?>
          <configuration>
            <system.webServer>
              <handlers>
                <add name="iisnode" path="server.js" verb="*" modules="iisnode" />
              </handlers>
              <rewrite>
                <rules>
                  <rule name="StaticContent">
                    <action type="Rewrite" url="public{REQUEST_URI}" />
                    <conditions>
                      <add input="{REQUEST_FILENAME}" matchType="IsFile" />
                    </conditions>
                  </rule>
                  <rule name="DynamicContent">
                    <conditions>
                      <add input="{REQUEST_FILENAME}" matchType="IsFile" negate="true" />
                    </conditions>
                    <action type="Rewrite" url="server.js" />
                  </rule>
                </rules>
              </rewrite>
              <iisnode 
                nodeProcessCommandLine="node"
                watchedFiles="web.config;*.js"
                loggingEnabled="true"
                logDirectory="iisnode" />
            </system.webServer>
          </configuration>
          EOF
          
          # Create server.js for serving static files
          cat > deployment/server.js << EOF
          import express from 'express';
          import path from 'path';
          import { fileURLToPath } from 'url';

          const __dirname = path.dirname(fileURLToPath(import.meta.url));
          const app = express();
          const PORT = process.env.PORT || 8080;

          // Serve static files
          app.use(express.static(path.join(__dirname, 'public')));

          // Serve index.html for all routes (SPA fallback)
          app.get('*', (req, res) => {
            res.sendFile(path.join(__dirname, 'public', 'index.html'));
          });

          app.listen(PORT, () => {
            console.log(\`Server running on port \${PORT}\`);
          });
          EOF
          
          # Create a production package.json
          cat > deployment/package.json << EOF
          {
            "name": "sales-inquiry-azure",
            "version": "1.0.0",
            "type": "module",
            "engines": {
              "node": ">=20.0.0"
            },
            "scripts": {
              "start": "node server.js"
            },
            "dependencies": {
              "express": "^4.18.2"
            }
          }
          EOF
          
          # Install only express in the deployment folder
          cd deployment
          npm install --omit=dev --no-package-lock
          
          # Zip everything for deployment
          zip -r ../release.zip ./*

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: node-app
          path: release.zip
          retention-days: 1

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: node-app

      - name: Unzip artifact for deployment
        run: unzip release.zip
      
      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_886E565E15F54F64825AFC8382A0E7EA }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_D814736B79FA4FBC95BEDB87DF16ECCF }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_51420C1A3F184E88ADC3E862DB86A4EF }}

      - name: 'Deploy to Azure Web App'
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'SalesInquiryGroup'
          slot-name: 'Production'
          package: .
          
      - name: Set App Settings
        uses: azure/appservice-settings@v1
        with:
          app-name: 'SalesInquiryGroup'
          app-settings-json: |
            [
              {
                "name": "NODE_ENV",
                "value": "production"
              },
              {
                "name": "PORT",
                "value": "8080"
              },
              {
                "name": "WEBSITE_NODE_DEFAULT_VERSION",
                "value": "~20"
              },
              {
                "name": "SCM_DO_BUILD_DURING_DEPLOYMENT",
                "value": "false"
              },
              {
                "name": "WEBSITE_RUN_FROM_PACKAGE",
                "value": "0"
              }
            ]
