name: Build and deploy Node.js app to Azure Web App - SalesInquiryGroup

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - name: Set up Node.js version
        uses: actions/setup-node@v3
        with:
          node-version: '20.x'

      - name: Install dependencies
        run: npm install

      - name: Create simplified build script
        run: |
          cat > build.js << 'EOF'
          import { execSync } from 'child_process';
          import fs from 'fs';
          import path from 'path';
          import { fileURLToPath } from 'url';

          const __dirname = path.dirname(fileURLToPath(import.meta.url));
          
          console.log('Starting simplified build process...');

          // Create dist directory
          const distDir = path.resolve(__dirname, 'dist');
          if (!fs.existsSync(distDir)) {
            fs.mkdirSync(distDir, { recursive: true });
          }
          
          const publicDir = path.resolve(distDir, 'public');
          if (!fs.existsSync(publicDir)) {
            fs.mkdirSync(publicDir, { recursive: true });
          }

          // Build client application
          try {
            // First build the client application with Vite
            console.log('Building client application...');
            execSync('npx vite build --outDir dist/public', { stdio: 'inherit' });
            
            // If the build fails or doesn't produce an index.html, fall back to copying files
            if (!fs.existsSync(path.resolve(publicDir, 'index.html'))) {
              console.log('Vite build failed to produce index.html, falling back to copying client files...');
              execSync('cp -r client/* dist/public/', { stdio: 'inherit' });
              
              // Create a proper index.html that references compiled JavaScript, not TSX
              fs.writeFileSync(
                path.resolve(publicDir, 'index.html'),
                '<!DOCTYPE html>\n<html lang="en">\n  <head>\n    <meta charset="UTF-8" />\n    <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1" />\n    <title>Sales Inquiry Group</title>\n  </head>\n  <body>\n    <div id="root"></div>\n    <script type="module" src="./index.js"></script>\n  </body>\n</html>'
              );
              
              // Create a simple index.js that displays something
              fs.writeFileSync(
                path.resolve(publicDir, 'index.js'),
                'document.getElementById(\'root\').innerHTML = \'<div style="text-align:center; padding:50px;"><h1>Sales Inquiry Group</h1><p>Application is loading...</p></div>\';\nconsole.log(\'Application initialized\');'
              );
            }
          } catch (error) {
            console.error('Failed to build client files:', error);
            process.exit(1);
          }

          // Build backend
          console.log('Building backend...');
          try {
            execSync('npx esbuild server/index.ts --platform=node --packages=external --bundle --format=esm --outdir=dist', { stdio: 'inherit' });
          } catch (error) {
            console.error('Failed to build backend:', error);
            process.exit(1);
          }

          console.log('Build completed successfully!');
          EOF

      - name: Run simplified build
        run: node build.js

      - name: Zip artifact for deployment
        run: |
          # Remove unnecessary files before zipping
          rm -rf node_modules
          rm -rf .git
          # Install only production dependencies
          npm ci --only=production
          # Create a more optimized zip file
          zip -r release.zip . -x "*.git*" "*.github*" "*.vscode*" "*.idea*" "*.DS_Store" "*.log"

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: node-app
          path: release.zip
          retention-days: 1

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    permissions:
      id-token: write #This is required for requesting the JWT
      contents: read #This is required for actions/checkout

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: node-app

      - name: Unzip artifact for deployment
        run: unzip release.zip

      - name: Login to Azure
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_886E565E15F54F64825AFC8382A0E7EA }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_D814736B79FA4FBC95BEDB87DF16ECCF }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_51420C1A3F184E88ADC3E862DB86A4EF }}

      - name: 'Deploy to Azure Web App'
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v2
        with:
          app-name: 'SalesInquiryGroup'
          slot-name: 'Production'
          package: .
          startup-command: 'node server/azure-entry.js'
            
