name: Build and deploy Node.js app to Azure Web App - SalesInquiryGroup

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - name: Set up Node.js version
        uses: actions/setup-node@v3
        with:
          node-version: '20.x'
          cache: 'npm'

      # Increase Node.js memory limit significantly
      - name: Configure Node options
        run: |
          echo "NODE_OPTIONS=--max_old_space_size=12288" >> $GITHUB_ENV
          echo "Memory limit increased to 12GB"

      - name: Install dependencies
        run: |
          # Use smaller dependency set if possible
          npm ci --no-audit --prefer-offline --production=false
        env:
          NODE_OPTIONS: "--max_old_space_size=12288"

      - name: Build application in chunks
        run: |
          # Use a memory-optimized build approach
          NODE_OPTIONS="--max_old_space_size=12288" npm run build
        env:
          NODE_ENV: production

      - name: Create deployment package
        run: |
          # Create a production-ready package
          mkdir -p deployment
          
          # Copy built files and necessary assets
          cp -r dist deployment/
          
          # Copy package.json and modify it for production
          node --max_old_space_size=12288 -e "
            const fs = require('fs');
            const pkg = require('./package.json');
            
            // Keep only what's needed for production
            const newPkg = {
              name: pkg.name,
              version: pkg.version,
              type: pkg.type,
              engines: { node: '~20' },
              scripts: {
                start: 'node --max-old-space-size=4096 dist/index.js'
              },
              dependencies: pkg.dependencies
            };
            
            // Remove dev dependencies
            delete newPkg.devDependencies;
            delete newPkg.optionalDependencies;
            
            // Write the modified package.json
            fs.writeFileSync('./deployment/package.json', JSON.stringify(newPkg, null, 2));
          "
          
          # Create a startup file for Azure with memory optimization
          cat > deployment/startup.js << EOF
          // startup.js - Azure startup script with memory optimization
          const { spawn } = require('child_process');
          const path = require('path');
          
          // Log the environment for debugging
          console.log('Starting application with environment:');
          console.log('NODE_ENV:', process.env.NODE_ENV);
          console.log('PORT:', process.env.PORT);
          console.log('Current directory:', process.cwd());
          
          try {
            console.log('Files in directory:', require('fs').readdirSync('.'));
            console.log('Files in dist directory:', require('fs').readdirSync('./dist'));
          } catch (err) {
            console.error('Error listing files:', err);
          }
          
          // Start the application with memory optimization
          const app = spawn('node', ['--max-old-space-size=4096', 'dist/index.js'], {
            stdio: 'inherit',
            env: { ...process.env, NODE_ENV: 'production' }
          });
          
          app.on('error', (err) => {
            console.error('Failed to start application:', err);
            process.exit(1);
          });
          
          app.on('exit', (code) => {
            console.log('Application exited with code:', code);
            process.exit(code);
          });
          EOF
          
          # Create web.config for Azure with memory settings
          cat > deployment/web.config << EOF
          <?xml version="1.0" encoding="utf-8"?>
          <configuration>
            <system.webServer>
              <handlers>
                <add name="iisnode" path="startup.js" verb="*" modules="iisnode" />
              </handlers>
              <rewrite>
                <rules>
                  <rule name="nodejs">
                    <match url="(.*)" />
                    <conditions>
                      <add input="{REQUEST_FILENAME}" matchType="IsFile" negate="true" />
                    </conditions>
                    <action type="Rewrite" url="startup.js" />
                  </rule>
                </rules>
              </rewrite>
              <iisnode 
                nodeProcessCommandLine="node --max-old-space-size=4096"
                watchedFiles="*.js;iisnode.yml"
                loggingEnabled="true"
                logDirectory="iisnode"
                debuggingEnabled="true"
                maxConcurrentRequestsPerProcess="1024"
                maxNamedPipeConnectionRetry="100"
                namedPipeConnectionRetryDelay="250"
                maxNamedPipeConnectionPoolSize="512"
                maxNamedPipePooledConnectionAge="30000"
                initialRequestBufferSize="4096"
                maxRequestBufferSize="65536"
              />
            </system.webServer>
          </configuration>
          EOF
          
          # Create a basic .env file
          echo "NODE_ENV=production" > deployment/.env
          
          # Install dependencies in the deployment directory
          cd deployment
          npm install --omit=dev --no-audit --prefer-offline
          
          # Zip everything for deployment
          zip -r ../release.zip ./*

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: node-app
          path: release.zip
          retention-days: 1

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: node-app

      - name: Unzip artifact for deployment
        run: unzip release.zip
      
      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_886E565E15F54F64825AFC8382A0E7EA }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_D814736B79FA4FBC95BEDB87DF16ECCF }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_51420C1A3F184E88ADC3E862DB86A4EF }}

      - name: 'Deploy to Azure Web App'
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'SalesInquiryGroup'
          slot-name: 'Production'
          package: .
          
      - name: Set App Settings
        uses: azure/appservice-settings@v1
        with:
          app-name: 'SalesInquiryGroup'
          app-settings-json: |
            [
              {
                "name": "NODE_ENV",
                "value": "production"
              },
              {
                "name": "PORT",
                "value": "5000"
              },
              {
                "name": "WEBSITE_NODE_DEFAULT_VERSION",
                "value": "~20"
              },
              {
                "name": "SCM_DO_BUILD_DURING_DEPLOYMENT",
                "value": "false"
              },
              {
                "name": "WEBSITE_MEMORY_LIMIT_MB",
                "value": "4096"
              },
              {
                "name": "WEBSITE_RUN_FROM_PACKAGE",
                "value": "0"
              },
              {
                "name": "NODE_OPTIONS",
                "value": "--max_old_space_size=4096"
              }
            ]
