name: Deploy to Azure

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '20.x'

    - name: Install dependencies
      run: |
        # Clean install to ensure all dependencies are installed
        npm ci
        # Verify React is installed
        ls -la node_modules/react || npm install react react-dom @types/react @types/react-dom

    - name: Build application
      run: |
        # Build the application
        npm run build

    - name: Prepare for deployment
      run: |
        # Create deployment directory
        mkdir -p deploy
        
        # Copy necessary files
        cp -r dist deploy/
        cp package.json deploy/
        
        # Create production package.json
        node -e "
          const fs = require('fs');
          const pkg = JSON.parse(fs.readFileSync('./package.json'));
          const deployPkg = {
            name: pkg.name,
            version: pkg.version,
            type: pkg.type,
            engines: pkg.engines,
            scripts: { start: 'node dist/index.js' },
            dependencies: {
              ...pkg.dependencies,
              'react': pkg.dependencies.react,
              'react-dom': pkg.dependencies['react-dom']
            }
          };
          fs.writeFileSync('./deploy/package.json', JSON.stringify(deployPkg, null, 2));
        "
        
        # Create web.config for Azure
        echo '<?xml version="1.0" encoding="utf-8"?>
        <configuration>
          <system.webServer>
            <handlers>
              <add name="iisnode" path="dist/index.js" verb="*" modules="iisnode" />
            </handlers>
            <rewrite>
              <rules>
                <rule name="nodejs">
                  <match url="(.*)" />
                  <conditions>
                    <add input="{REQUEST_FILENAME}" matchType="IsFile" negate="true" />
                  </conditions>
                  <action type="Rewrite" url="dist/index.js" />
                </rule>
              </rules>
            </rewrite>
          </system.webServer>
        </configuration>' > deploy/web.config
        
        # Install production dependencies
        cd deploy
        npm install --omit=dev

    - name: Login to Azure
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Deploy to Azure Web App
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'SalesInquiryGroup'
        slot-name: 'Production'
        package: './deploy'

    - name: Configure App Settings
      uses: azure/appservice-settings@v1
      with:
        app-name: 'SalesInquiryGroup'
        app-settings-json: |
          [
            {
              "name": "NODE_ENV",
              "value": "production"
            },
            {
              "name": "PORT",
              "value": "8080"
            },
            {
              "name": "WEBSITE_NODE_DEFAULT_VERSION",
              "value": "~20"
            }
            ]
